# Script to launch servers
# Using http://docs.ansible.com/ansible/gce_module.html
# Requirement on MacOS X: pip install apache-libcloud

- name: Create instance(s)
  hosts: localhost
  gather_facts: no
  connection: local
  tags:
     - launchinstance
  roles:
     - launch

- name: Manage new instances
  hosts: new_instances
  connection: ssh
  sudo: True
  roles:
     - configure
